// ================================================================
// wine-data.js
// 역할: 초기 와인 테이스팅 노트 데이터 (Firebase에 없을 때 시드)
// 의존성: 없음
// ================================================================

export const INITIAL_WINES = [
  {
    id: 'wine_001',
    name: '샤스 스플린',
    vintage: 2020,
    region: '보르도, 프랑스',
    variety: 'Cabernet Sauvignon / Merlot 블렌딩',
    vivinoRating: null,
    vivinoEstimated: true,
    criticRatings: [],
    color: '짙은 루비색',
    nose: '쿰쿰한 향, 젖은 낙엽향',
    palate: '매우 떫고 쓰며, 약간 맹맹한 맛. 과실미가 크게 느껴지지는 않음.',
    structure: { sweetness: 0.5, tannin: 4.0, acidity: null, alcohol: null },
    note: '당도 0.5, 탄닌 4.0. 짙은 루비색.',
    imageUrl: null,
    createdAt: '2024-01-01',
  },
  {
    id: 'wine_002',
    name: '제라르 베르트랑 샤또 로스피딸레',
    vintage: null,
    region: '랑그독, 프랑스',
    variety: '블렌딩',
    vivinoRating: null,
    vivinoEstimated: true,
    criticRatings: [],
    color: null,
    nose: '우유향, 꽃향, 화장품향, 샤프란향',
    palate: '옅은 과실미, 복합적인 느낌.',
    structure: { sweetness: 1.0, tannin: 2.0, acidity: null, alcohol: null },
    note: '당도 1.0, 탄닌 2.0.',
    imageUrl: null,
    createdAt: '2024-01-02',
  },
  {
    id: 'wine_003',
    name: 'Casa Castillo El Molar',
    vintage: 2019,
    region: '후미야, 스페인',
    variety: 'Monastrell',
    vivinoRating: null,
    vivinoEstimated: true,
    criticRatings: [],
    color: null,
    nose: '붉은 과실향, 신선한 자두, 체리',
    palate: '피노누아와 비슷한 점이 있음. 오크터치는 없는 것처럼 느껴짐. 산도가 강하지만 약간의 당도가 이를 받쳐줌.',
    structure: { sweetness: 1.5, tannin: 1.0, acidity: 3.5, alcohol: null },
    note: '당도 1.5/5, 산도 3.5/5, 탄닌 1/5. 보르도 계열보다 확실히 탄닌이 적음.',
    imageUrl: null,
    createdAt: '2024-01-03',
  },
  {
    id: 'wine_004',
    name: 'Chateau Mondazur Grand Vin Pecharmant',
    vintage: 2020,
    region: '페샤르망, 프랑스',
    variety: 'Merlot',
    vivinoRating: null,
    vivinoEstimated: true,
    criticRatings: [],
    color: '매우 짙은 루비색',
    nose: '검붉은 과실향, 다크 초콜렛향, 바닐라향',
    palate: '진한 과즙미가 뿜어져 나오는 당도. 짙은 탄닌, 알콜감, 약간의 산도가 받쳐줌. 오크 숙성된 메를로 느낌.',
    structure: { sweetness: null, tannin: null, acidity: null, alcohol: null },
    note: '오크 숙성된 메를로 느낌.',
    imageUrl: null,
    createdAt: '2024-01-04',
  },
  {
    id: 'wine_005',
    name: 'Domaine de Suremain Mercurey 1er Cru Les Croichots',
    vintage: null,
    region: '부르고뉴 메르퀴레, 프랑스',
    variety: 'Pinot Noir',
    vivinoRating: null,
    vivinoEstimated: true,
    criticRatings: [],
    color: '버건디색',
    nose: '경쾌한 딸기, 체리, 바닐라향',
    palate: '탄닌, 산도, 과실미의 균형이 잘 어우러짐. 와인의 눈물이 빠르게 흘러내려 바디감은 약한 편이나 탄닌이 있는 편. [1시간 후] 과즙미가 더 풍성해짐.',
    structure: { sweetness: null, tannin: null, acidity: null, alcohol: null },
    note: '오픈 후 시간이 지날수록 풍성해지는 와인.',
    imageUrl: null,
    createdAt: '2024-01-05',
  },
  {
    id: 'wine_006',
    name: 'Conundrum Red Blend',
    vintage: null,
    region: '캘리포니아, 미국',
    variety: 'Red Blend',
    vivinoRating: null,
    vivinoEstimated: true,
    criticRatings: [],
    color: '투명하지만 진한 자두색',
    nose: '감초향, 초콜렛향, 진한 스파이스',
    palate: '잔당감이 꽤 있는 것처럼 느껴짐. 산도가 꽤 있고, 중상 정도의 탄닌과 강한 알콜감. 당도가 강조됨에 따라 복합도가 조금 떨어지는 경향.',
    structure: { sweetness: null, tannin: null, acidity: null, alcohol: null },
    note: '당도 강조로 복합도가 다소 떨어짐.',
    imageUrl: null,
    createdAt: '2024-01-06',
  },
  {
    id: 'wine_007',
    name: 'Jean Etienne Chermette Moulin-à-Vent',
    vintage: null,
    region: '보졸레 무랭아방, 프랑스',
    variety: 'Gamay',
    vivinoRating: null,
    vivinoEstimated: true,
    criticRatings: [],
    color: '진한 버건디색',
    nose: '허브향, 신선한 체리향',
    palate: '과실미가 절제되어 있어 드라이. 당도가 낮고 약간의 산도가 뒷받침함.',
    structure: { sweetness: null, tannin: null, acidity: null, alcohol: null },
    note: '드라이한 스타일.',
    imageUrl: null,
    createdAt: '2024-01-07',
  },
  {
    id: 'wine_008',
    name: 'Maison Matisco Saint-Véran Chardonnay',
    vintage: 2020,
    region: '마꼬네 생베랑, 프랑스',
    variety: 'Chardonnay',
    vivinoRating: null,
    vivinoEstimated: true,
    criticRatings: [],
    color: '노을빛 황금색',
    nose: '시트러스향, 토스티하고 오키한 향, 진한 과실미, 타임·로즈마리향',
    palate: '청사과와 같은 과실미. 산도와 당도가 조화로워 복합미가 있는 와인.',
    structure: { sweetness: null, tannin: null, acidity: null, alcohol: null },
    note: '화이트 와인. 복합미 있는 샤르도네.',
    imageUrl: null,
    createdAt: '2024-01-08',
  },
  {
    id: 'wine_009',
    name: 'Unshackled Red Blend',
    vintage: null,
    region: '캘리포니아, 미국',
    variety: 'Red Blend',
    vivinoRating: null,
    vivinoEstimated: true,
    criticRatings: [],
    color: '진한 루비색',
    nose: '약한 감초와 스파이스, 약간의 초콜렛 뉘앙스',
    palate: 'The Prisoner와 같은 빈야드 제품이지만 복합미가 떨어짐. 바닐라 뉘앙스는 거의 없음. 과실미가 뿜어져나오지만 산도가 뒷받침되지 않아 복합미가 떨어짐.',
    structure: { sweetness: null, tannin: null, acidity: null, alcohol: null },
    note: 'The Prisoner 대비 복합미 부족.',
    imageUrl: null,
    createdAt: '2024-01-09',
  },
  {
    id: 'wine_010',
    name: '오린 스위프트 앱스트랙트 (Orin Swift Abstract)',
    vintage: null,
    region: '캘리포니아, 미국',
    variety: 'Grenache / Petite Sirah / Syrah',
    vivinoRating: null,
    vivinoEstimated: true,
    criticRatings: [],
    color: '진한 검붉은 과실색',
    nose: '검붉은 과실향, 초콜렛, 바닐라',
    palate: '흘러넘치는 과실미. 미약한 산도. 굵직한 무게감.',
    structure: { sweetness: null, tannin: null, acidity: null, alcohol: null },
    note: '풀바디. 굵직한 무게감.',
    imageUrl: null,
    createdAt: '2024-01-10',
  },
  {
    id: 'wine_011',
    name: 'The Hilt Estate Pinot Noir',
    vintage: null,
    region: '산타 바바라, 미국',
    variety: 'Pinot Noir',
    vivinoRating: null,
    vivinoEstimated: true,
    criticRatings: [],
    color: '맑고 투명한 루비색',
    nose: '라즈베리향, 흘러넘치는 과실미',
    palate: '산도가 어우러지는 과실미. 중급 정도의 탄닌으로 과하지 않음. Domaine de Suremain과 뉘앙스가 비슷하지만 보다 새콤하고 상큼한 느낌.',
    structure: { sweetness: null, tannin: null, acidity: null, alcohol: null },
    note: 'Domaine de Suremain과 비슷하지만 더 상큼함.',
    imageUrl: null,
    createdAt: '2024-01-11',
  },
  {
    id: 'wine_012',
    name: 'Particular Garnacha Viñas Centenarias',
    vintage: null,
    region: '스페인',
    variety: 'Garnacha',
    vivinoRating: null,
    vivinoEstimated: true,
    criticRatings: [],
    color: '짙은 루비색',
    nose: '짙은 미네랄리티, 약간의 페트롤 또는 화장품 같은 질감',
    palate: '라즈베리보다 자두에 가까운 붉은 과실미. 강한 탄닌감. 바디감이 꽤 있음.',
    structure: { sweetness: null, tannin: null, acidity: null, alcohol: null },
    note: '미네랄리티가 강조된 가르나차.',
    imageUrl: null,
    createdAt: '2024-01-12',
  },
  {
    id: 'wine_013',
    name: 'Domaine Michel Gros Bourgogne Hautes-Côtes de Nuits',
    vintage: 2022,
    region: '부르고뉴, 프랑스',
    variety: 'Pinot Noir',
    vivinoRating: null,
    vivinoEstimated: true,
    criticRatings: [],
    color: null,
    nose: '약간의 버섯향, 젖은 나뭇잎 향, 라즈베리',
    palate: '산미가 높은, 산지오베제급으로 유달리 강조된 산도. 절제된 과실미. 어느 정도 탄닌. [30분 디캔팅 후] 딸기·체리 향 물씬, 탄닌 둥그러지나 산도는 여전.',
    structure: { sweetness: null, tannin: null, acidity: null, alcohol: null },
    note: '이 가격대 부르고뉴로는 가성비 이태리 와인들이 많을 것 같음.',
    imageUrl: null,
    createdAt: '2024-01-13',
  },
  {
    id: 'wine_014',
    name: "L'Hydrophobe Brouille",
    vintage: 2022,
    region: '프랑스',
    variety: '알 수 없음',
    vivinoRating: null,
    vivinoEstimated: true,
    criticRatings: [],
    color: null,
    nose: '신선한 라즈베리향',
    palate: '굉장히 맛있었음.',
    structure: { sweetness: null, tannin: null, acidity: null, alcohol: null },
    note: '간단 메모. 매우 인상적이었음.',
    imageUrl: null,
    createdAt: '2024-01-14',
  },
  {
    id: 'wine_015',
    name: 'Château Cantemerle Haut-Médoc',
    vintage: 2020,
    region: '오메독, 보르도, 프랑스',
    variety: 'Cabernet Sauvignon / Merlot 블렌딩',
    vivinoRating: null,
    vivinoEstimated: true,
    criticRatings: [],
    color: '진한 루비색',
    nose: '밀크초콜렛향, 신선한 블랙베리·자두, 우유·연유 같은 느낌',
    palate: '검은 과실 베이스지만 붉은 과실 느낌도 있음. 흙향·낙엽·삼나무 뉘앙스는 적은 편. 약 12개월 오크터치 추정. 오밀조밀한 탄닌.',
    structure: { sweetness: null, tannin: null, acidity: null, alcohol: null },
    note: '일반적인 보르도 블렌딩 대비 신선한 과실미가 강조됨.',
    imageUrl: null,
    createdAt: '2024-01-15',
  },
  {
    id: 'wine_016',
    name: 'Slander Pinot Noir',
    vintage: 2022,
    region: '오레곤, 미국',
    variety: 'Pinot Noir',
    vivinoRating: null,
    vivinoEstimated: true,
    criticRatings: [],
    color: '버건디빛',
    nose: '과실미 넘치는 피노누아, 산뜻한 체리·블랙베리, 가벼운 로즈마리·타임향',
    palate: '농축된 과실미이지만 적당한 당도로 절제됨. 탄닌 적음. 오크터치 6개월~1년. 굉장히 우아한 피노누아. 부르고뉴 스타일과는 다르며 끝맛이 산뜻함.',
    structure: { sweetness: null, tannin: null, acidity: null, alcohol: null },
    note: '매우 우아하게 만든 피노누아.',
    imageUrl: null,
    createdAt: '2024-01-16',
  },
  {
    id: 'wine_017',
    name: 'Lingua Franca Estate Pinot Noir',
    vintage: 2021,
    region: '오레곤, 미국',
    variety: 'Pinot Noir',
    vivinoRating: null,
    vivinoEstimated: true,
    criticRatings: [],
    color: '짙은 가넷',
    nose: '라즈베리, 딸기, 사워체리의 고혹적인 향기',
    palate: '상당한 산미. 탄닌이 혀를 감싸안을 정도. 오크터치 6개월 추정. 미국 와인이지만 바닐라·초콜렛보다 과실미에 집중한 스타일.',
    structure: { sweetness: null, tannin: null, acidity: null, alcohol: null },
    note: '고혹적인 과실미와 상당한 산미의 조화.',
    imageUrl: null,
    createdAt: '2024-01-17',
  },
  {
    id: 'wine_018',
    name: 'Volcanes Tectónica Pinot Noir',
    vintage: null,
    region: '칠레',
    variety: 'Pinot Noir',
    vivinoRating: null,
    vivinoEstimated: true,
    criticRatings: [],
    color: '투명한 루비색',
    nose: '과실미 (피라진향 없음)',
    palate: '카멜로드 등 오크숙성 스타일 대비 과실미 강조. 산도와 당도 조화롭게 균형. 탄닌감 어느 정도 있음. 가격대 대비 레지오날급과 비교 가능. 떼루아 뉘앙스는 약함.',
    structure: { sweetness: null, tannin: null, acidity: null, alcohol: null },
    note: '가성비 칠레 피노누아. 피라진향 없음이 장점.',
    imageUrl: null,
    createdAt: '2024-01-18',
  },
  {
    id: 'wine_019',
    name: 'Maggy Hawk Stormin',
    vintage: 2018,
    region: '앤더슨 밸리, 캘리포니아, 미국',
    variety: 'Pinot Noir',
    vivinoRating: null,
    vivinoEstimated: true,
    criticRatings: [],
    color: '투명한 버건디색 (피노누아 치고는 조금 어두운 색)',
    nose: '신선한 딸기·라즈베리·사워체리, 벨베티하고 밀키한 노즈, 검붉은 과실 뉘앙스 20%',
    palate: '당도와 산도의 밸런스가 매우 훌륭. 쨍한 산도를 과실미가 탄탄하게 뒷받침. 탄닌감 거의 없어 처음부터 둥글둥글. [30분 후] 산도 누그러지며 라즈베리·딸기 향이 밀키함과 만나 신선함 폭발.',
    structure: { sweetness: null, tannin: null, acidity: null, alcohol: null },
    note: '미국 피노누아이지만 검붉은 과실 뉘앙스가 독특. 포도줄기의 쌉쌀함이 미묘하게 느껴짐.',
    imageUrl: null,
    createdAt: '2024-01-19',
  },
  {
    id: 'wine_020',
    name: 'The Hilt Estate Pinot Noir',
    vintage: 2020,
    region: '산타 바바라, 미국',
    variety: 'Pinot Noir',
    vivinoRating: null,
    vivinoEstimated: true,
    criticRatings: [],
    color: '맑고 투명한 밝은 루비색',
    nose: '신선한 딸기·라즈베리, 은은한 바닐라·초콜렛, 포도줄기 뉘앙스 미약',
    palate: '과실미 폭발 스타일. 오크터치 6개월~1년 추정. 탄닌 매우 둥글어 부담 없음. 잔당감 없음. 여운이 긴 편. [30분 후] 연유 같은 젖산 발효 뉘앙스 살짝. 매기호크만큼은 아님.',
    structure: { sweetness: null, tannin: null, acidity: null, alcohol: null },
    note: '미국 피노누아의 전형성. 복합미 있음. 떼루아 뉘앙스는 거의 없음.',
    imageUrl: null,
    createdAt: '2024-01-20',
  },
  {
    id: 'wine_021',
    name: 'Bourgogne Hautes-Côtes de Nuits',
    vintage: 2022,
    region: '부르고뉴, 프랑스',
    variety: 'Pinot Noir',
    vivinoRating: null,
    vivinoEstimated: true,
    criticRatings: [],
    color: '매우 투명하고 밝은 루비빛',
    nose: '다진 라즈베리의 진한 산도, 얼씨한 느낌, 미네랄리티',
    palate: '오크 뉘앙스 거의 없음. 부르고뉴치고 과실미 풍성. 피니시가 꽤 길며 삼키고 나서도 산도가 입안에 남음. 탄닌은 오밀조밀하고 둥글어 혀를 쪼이는 느낌 적음.',
    structure: { sweetness: null, tannin: null, acidity: null, alcohol: null },
    note: '얼씨함이 있지만 과실미가 유독 강조되는 부르고뉴.',
    imageUrl: null,
    createdAt: '2024-01-21',
  },
  {
    id: 'wine_022',
    name: 'Domaine Serene Evenstad Reserve Pinot Noir',
    vintage: 2018,
    region: '오레곤, 미국',
    variety: 'Pinot Noir',
    vivinoRating: null,
    vivinoEstimated: true,
    criticRatings: [],
    color: '피노누아 치고는 조금 더 검은 계열에 가까운 진한 루비색',
    nose: '검붉은 계열 과실미 (자두·체리), 바닐라·토스트 뉘앙스',
    palate: '땄을 때는 피니시에서 쓴맛. [10분 후] 산도 올라오며 과실미 빛을 발함. 오크터치 6개월~1년 추정. 말로락틱 발효 뉘앙스 거의 없음.',
    structure: { sweetness: null, tannin: null, acidity: null, alcohol: null },
    note: '오픈 후 시간이 필요한 와인. 쓴맛이 얼씨한 느낌인지 불확실.',
    imageUrl: null,
    createdAt: '2024-01-22',
  },
  {
    id: 'wine_023',
    name: 'Patricia Green Cellars Estate Vineyard Ribbon Ridge Pinot Noir',
    vintage: 2021,
    region: '리본 릿지, 오레곤, 미국',
    variety: 'Pinot Noir',
    vivinoRating: null,
    vivinoEstimated: true,
    criticRatings: [],
    color: '투명한 가넷',
    nose: '붉은 과실이 치고 들어오는 어택, 얼씨함이 강조',
    palate: '미국 피노누아이지만 프랑스 피노누아에 가깝게 느껴짐. 과실미가 인위적인 딸기 시럽에 가까워 불호. 탄닌 매우 약함. 오크 뉘앙스는 있으나 바닐라·밀키한 뉘앙스 없음.',
    structure: { sweetness: null, tannin: null, acidity: null, alcohol: null },
    note: '과실미가 인위적인 딸기 시럽 느낌이라 불호.',
    imageUrl: null,
    createdAt: '2024-01-23',
  },
  {
    id: 'wine_024',
    name: "Two Hands Bella's Garden Shiraz",
    vintage: 2021,
    region: '맥클라렌 베일, 호주',
    variety: 'Shiraz',
    vivinoRating: null,
    vivinoEstimated: true,
    criticRatings: [],
    color: '진한 버건디색',
    nose: '검은 과실미, 바닐라·초콜렛 뉘앙스 강함, 포도줄기의 쌉싸름함',
    palate: '호주 쉬라 중 비교적 우아한 편. 실키함·밀키함. 약한 정도의 스파이스, 피니시의 타임향. 산도가 훌륭하게 뒷받침. 탄닌감 불편하지 않은 수준. 오크숙성 최소 1년 이상 추정. 알콜감 강함.',
    structure: { sweetness: null, tannin: null, acidity: null, alcohol: null },
    note: '블라인드라면 호주 쉬라라고 생각 못했을 정도로 부드러움.',
    imageUrl: null,
    createdAt: '2024-01-24',
  },
];
